CREATE SEQUENCE GEN_ID_USUARIO START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE T_CN_USUARIO (
    ID_USUARIO INTEGER DEFAULT GEN_ID_USUARIO.NEXTVAL NOT NULL PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    SENHA VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);

CREATE SEQUENCE GEN_ID_TRANSPORTE INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCYCLE NOCACHE;

CREATE TABLE T_CN_TRANSPORTE (
    ID_TRANSPORTE NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    TIPO_TRANSPORTE NVARCHAR2(255) NOT NULL,
    DISTANCIA_KM NUMBER(10,2) NOT NULL,
    DT_USO DATE NOT NULL,
    EMISSAO_CALCULADA NUMBER(10,4) NOT NULL,
    EMISSAO_PERMITIDA_ISO NUMBER(10, 4) DEFAULT 2.5 NOT NULL,
    CONFORME_ISO CHAR(1)
);

ALTER TABLE T_CN_TRANSPORTE ADD CONSTRAINT FK_TRANSPORTE_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_CN_USUARIO(ID_USUARIO);

CREATE SEQUENCE GEN_ID_ITEM INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCYCLE NOCACHE;

CREATE TABLE T_CN_ITEM_ELETRICO (
    ID_ITEM NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    NOME_ITEM NVARCHAR2(255) NOT NULL,
    CONSUMO_KWH NUMBER(10,2) NOT NULL,
    DT_USO DATE NOT NULL,
    EMISSAO_CALCULADA NUMBER(10,4) NOT NULL
);

ALTER TABLE T_CN_ITEM_ELETRICO ADD CONSTRAINT FK_ITEM_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_CN_USUARIO(ID_USUARIO);